# -*- coding: utf-8 -*-
"""4th May.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T48EsXQawtnWwVdXCSjksHQs12ADd8Wt
"""



a=1.5
b=15.6
c=b/a
print(c)

a=int(input("value for a"))
b=int(input("value for b"))
c=int(input("value for c"))

if(a==b | b==c):
    print("good")
else:
    print("bad")