# -*- coding: utf-8 -*-
"""19th May.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QQexFIiPn_uaJ8SAVplNvYj-j7CjVDoP
"""

#To remove duplicates use set(a). To print duplicates, something like:
L=[1,1,1,1,1,1,1,2,2,2,3,3,3]
set(L)

"""```
To remove duplicates use set(a). To print duplicates, something like:

```
"""

#set example
L=[1,1,1,1,1,1,1,2,2,2,3,3,3]
a = set(L)
for i in a:
  if(i==a):
    print("Amazing India")
  else:
    print("Increadible India")

L=[1,1,1,1,1,1,1,2,2,2,3,3,3]
a=set(L)

import statistics

List = [1,2,3,5,99,8,9]
def mean():
  print(statistics.mean(List))

def median():
  print(statistics.median(List))


mean()
median()